[options]
admin_passwd = master_password_caramia
db_host = db
db_port = 5432
db_user = milenitaOdoo
db_password = milenitapassword
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons